name: convert

on:
  push:
  workflow_dispatch:

concurrency:
  group: convert
  cancel-in-progress: true

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
        with:
          path: ild
      - uses: actions/checkout@v4
        with:
          repository: abbyxh/root2gltf
          ref: full_conversion
          path: root2gltf
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - uses: aidasoft/run-lcg-view@v4
        with:
          container: el9
          view-path: /cvmfs/sw-nightlies.hsf.org/key4hep
          run: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh" 
            nvm install 16
            cd root2gltf
            ls /home/runner/work/Phoenix-ILD/Phoenix-ILD/root2gltf/node_modules
            ls /home/runner/work/Phoenix-ILD/Phoenix-ILD/root2gltf/node_modules/canvas
            npm ci
            cd bin
            python conversion_xml2gltf_autoConfig.py \
              -cm $K4GEO/ILD/compact/ILD_l5_o1_v02/ILD_l5_o1_v02.xml \
              -cn_in ILD_l5_o1_v02.json



